### ISSUE TITLE
All progress bars are not showing

### ISSUE THREAD

**Issue by Zyin055** [DeadlyBossMods/DBM-BCC#6]
**Describe the bug**
Both when in a real boss encounter and when clicking the "Start test bars" button in General Options > Core & Gui, all types of progress bars are not visible. Normal DBM announcements, such as the "Test Mode Started..." announcement still works.

The progress bars worked on my Sunwell raid night 6/01/22 and stopped working the next night on 6/02/22. I did not update DBM or alter any DBM config options.

Edit 1: I discovered that deleting DBM-StatusBarTimers.lua and DBM-StatusBarTimers.lua.bak in WTF\Account\123456#1\SavedVariables folder fixes the issue, but of course that resets my bar settings so not exactly a perfect solution.

Edit 2: In Options > Timers > Bar Appearance the Alpha value for both Small Bar Options and Huge Bar Options somehow got set to 0. **_Setting these to 1 resolves the issue._** I have no idea how these got set to 0 since I haven't used this settings page since I first set up DBM classic 2 years ago.

**Do you have an error log of what happened?**
No LUA errors are produced.

**To Reproduce**

**Screenshots**
https://imgur.com/a/cDu1qP5

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of DeadlyBossMods are you using?**
2.5.36-bcc

**Was it working in a previous version? If yes, which was the last good one?**
The current version, 2.5.36-bcc, which I installed on 5/20/22.

**Additional context**
Another user on reddit posted having the same issue: https://www.reddit.com/r/wowaddons/comments/v3htok/no_dbm_bars/

**Comment by QartemisT** [comment]
Simply run `/run DBT:ResetSkin()` and it should fix itself. Likely caused by having a WeakAura installed such as one of the older "ability timeline" ones =]
