### ISSUE TITLE
Feature Request: Range Check Text Box only shows players with raid icons

### ISSUE THREAD

**Issue by perringaiden** [DeadlyBossMods/DBM-BCC#9]
On fights where teams are spread into groups and a marked player representing the place for that group to stack, it would be great if you could adjust the Range Check to only list people with a symbol.

Example is breaking up by group on Felmyst.  We want to have the marked people stay right on 23yds apart, but depending on who is marked, the list may not show the marked people when they're *just* in range.

**Comment by MysticalOS** [comment]
TBC is over at this point, and all time is beig focused on wrath and DF. While this is a feature DBM core supports, it's also very niche and I don't think using it in TBC at this point would be well understood so far in, so it's probably better to leave it alone anyways.

I may revisit this if there is ever a new tbc server/season.
